[platformio]
default_envs = jc4827w543

[env]
test_framework = unity

[env:jc4827w543]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.speed = 921600
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
lib_deps =
    moononournation/GFX Library for Arduino@1.4.7
    lvgl/lvgl@8.4.0

[env:native]
platform = native
build_flags = -std=gnu++17
build_src_filter = +<core/*>
test_build_src = yes
